# Generated by Django 3.2 on 2021-05-01 08:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0004_favoritearticles"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favoritearticles",
            unique_together={("article", "user")},
        ),
    ]
